:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\PetstoreApi
dotnet build src\PetstoreApi
echo Now, run the following to start the project: dotnet run -p src\PetstoreApi\PetstoreApi.csproj --launch-profile web.
echo.
