#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/PetStore.Api/ && \
    dotnet build src/PetStore.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/PetStore.Api/PetStore.Api.csproj --launch-profile web"
